### PR TITLE
Small Update

### PR DESCRIPTION
**Pull request by RyanisyydsTT**
Fixed Typo, added more plugin

### CODE REVIEW

**Comment by MagicTeaMC** [comment]
Use Big5 encoding please
image

**Comment by RyanisyydsTT** [comment]
圖片
forgot to save with Big5 .w.

**Comment by MagicTeaMC** [comment]
btw why rename .bat file name?

**Comment by RyanisyydsTT** [comment]
Preventing if I make the whole .bat error. 🤣

**Comment by MagicTeaMC** [comment]
Please just edit original file :)

**Pull request closed without merging**
